### ISSUE TITLE
AttachTo as right-click option on objects

### ISSUE THREAD

**Issue by KiritoKun223** [R3voA3/3den-Enhanced#113]
It would be a nice new function to have a right-click option on objects (maybe in the edit menu) to attach them to another object.

Example:

I place an object on the back of a truck 
![image](https://user-images.githubusercontent.com/25136302/93203335-8d68f180-f754-11ea-9c9a-9dede31d8885.png)

I can then right-click on the box (as in the picture) and select "attach To" and then you can select another object (the truck in this case) and the box will be attached with its relative position to the truck. 

There's already a function like that as a Zeus module in ZEN.

**Comment by R3voA3** [comment]
Thanks for the suggestions. It's something I have been investigating but haven't yet found a solution which is satisfiying.

**Comment by KiritoKun223** [comment]
You'll probably have to (somehow) get the relative position of 2 objects and attach them with the coordinates you get from that, I guess. As far as I know dedmen has made a script for getting the relativ position of objects, maybe that might help.

**Comment by R3voA3** [comment]
Getting the position is actually not a problem, but creating a reliable attribute. This would be the ideal scenario for a custom connection but seems they were never really implemented.

**Comment by AlexMason1** [comment]
@R3voA3 Dedmen told me he would like to know more about what you mean with custom connections, Maybe he can help make this possible.

**Comment by R3voA3** [comment]
Currently it doesn't seem like Eden Editor supports connections between two objects which execute a custom expression. Currently all available connections are handled inside the engine.

`class Group
{
	displayName = "Group to";
	data = "Group";
	color[] = {0,1,1,1};
	cursor = "3DENConnectGroup";
};`

So what we need is something like this:

`class Attach
{
	displayName = "Attach";
	expression = "_this # 0 attachTo _this #1"; //_this <array> with two objects ([fromObject, toObject]). Expression should then 
                                                                              be executed on the server
	color[] = {0,1,1,1};
	cursor = "3DENConnectGroup";
};`

**Comment by AlexMason1** [comment]
From Dedmen: that sounds doable, FT ticket plox

**Comment by R3voA3** [comment]
https://feedback.bistudio.com/T155116

**Comment by dedmen** [comment]
You still want the engine feature?

**Comment by R3voA3** [comment]
Sure =)

**Comment by KiritoKun223** [comment]
Hey, just something I found a second ago: https://community.bistudio.com/wiki/BIS_fnc_attachToRelative

This might be exactly what's needed.

**Comment by R3voA3** [comment]
https://youtu.be/JzZrFkSzspI
