### ISSUE TITLE
New inventory editor doesn't show ACE medical items

### ISSUE THREAD

**Issue by klausman** [R3voA3/3den-Enhanced#128]
As the subject says. Bandages, autoinjectors, blood, saline etc. are all missing from the new inventory manager. Vanilla inventory editor shows them just fine.

**Comment by R3voA3** [comment]
Thanks for letting me know. I'll investigate.

**Comment by R3voA3** [comment]
Seems that all these items are in the Bipod category because 

`"ACE_MapTools" call BIS_fnc_itemType;` Returns ["Item","AccessoryBipod"]

Guess I have to find a better way to sort items.

**Comment by R3voA3** [comment]
Issue has been fixed.
