### ISSUE TITLE
Bring Texture Viewer to the next level

### ISSUE THREAD

**Issue by R3voA3** [R3voA3/3den-Enhanced#135]
- [ ] Scan addon files instead of config, to get all the unused goodies
---
```
_paa = [];
_jpg = [];

{ 
    {
        _paa pushBack _x; //pushBackUnique not needed
    } forEach addonFiles [_x # 0, ".paa"];
    {
        _jpg pushBack _x; //pushBackUnique not needed
    } forEach addonFiles [_x # 0, ".jpg"];
} forEach allAddonsInfo;

systemChat ("PAA: " + str count _paa); //~37k files
systemChat ("JPG: " + str count _jpg); // ~ 4k files
```

**Comment by ConnorAU** [comment]
Three points on this.

First point: I tested this when doing my recent changes and it was mostly structure/vehicle textures. Not sure if that would be considered spam or not, as there is no real use for them other than on the associated object, but worth keeping in mind.

Second point: that code can be simplified.
```sqf
{ 
    _paa append addonFiles [_x # 0, ".paa"];    
    _jpg append addonFiles [_x # 0, ".jpg"];   
} forEach allAddonsInfo;
```

Third point: this addonFiles method won't detect images in .ebo addons, so a combination of both detection methods would be best to provide the most complete results.

**Comment by R3voA3** [comment]
Thanks for your feedback. I did some testing and yes, most of this stuff is vehicle textures and similar. 

I might keep the current method and add paths of hidden and useful textures manually, like those from firing drills and time trails.

**Comment by R3voA3** [comment]
Won't happen.
