### ISSUE TITLE
Group Marker Disabling Issue

### ISSUE THREAD

**Issue by JoeOakley52** [R3voA3/3den-Enhanced#145]
So making a mission and I have a script already that gives group markers but forgot I did.

Now my issue is when clicking "Reset and Disable" I get a error and when going in game it still shows EH group marker.

Here is a picture of debug error: https://gyazo.com/c7c551f01a5a8646dead025fcc263430

I also have deleted the custom attribute from my mission.SQM but still shows marker in game.

**Comment by R3voA3** [comment]
That's for the report, the issue will be fixed in the next release.
