### ISSUE TITLE
selected animation cell

### ISSUE THREAD

**Issue by topden** [R3voA3/3den-Enhanced#162]
http://joxi.ru/gmvlpEWT1R1W0A

can we make 1 cell closeable like cell 2 and so on? 
sry for my english.

**Comment by R3voA3** [comment]
Thanks for your feedback. I'll look into it.

**Comment by R3voA3** [comment]
I looked into it and noticed that I have already changed that. Animations are now in their own category and the ListBox was replaced with a ComboBox so save space.
