### ISSUE TITLE
coordinates (request)

### ISSUE THREAD

**Issue by topden** [R3voA3/3den-Enhanced#163]
is it possible to somehow add a function somewhere so that you can work with the coordinates of objects or coordinates relative to objects? 
like this https://forums.bohemia.net/forums/topic/204041-attachto-finder/

**Comment by R3voA3** [comment]
Can you be more specific? What do you want to achieve with that?

**Comment by topden** [comment]
I would like, for example, to put object A on object B and see the coordinates of object A relative to object B. So that you can use this information in the future for the "attachto" command

**Comment by R3voA3** [comment]
Ah okay. That's do-able I suppose.

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/110310236-9ac7b000-8002-11eb-95b6-f32a530bfc2e.png)

https://steamcommunity.com/sharedfiles/filedetails/?id=1387934106

Get this mod. It does exactly what you want and is a great addition to Eden Editor
