### ISSUE TITLE
Missing localisations

### ISSUE THREAD

**Issue by topden** [R3voA3/3den-Enhanced#170]
when I expose vehicle in the editor and do damage to it, errors in the RPT come out 
(for example this brdm2 from veteran mod)

10:40:16 String STR_ENH_DAMAGE_HITGLASS21 not found
10:40:16 String STR_ENH_DAMAGE_HITGLASS22 not found
10:40:16 String STR_ENH_DAMAGE_HITGLASS23 not found
10:40:16 String STR_ENH_DAMAGE_HITGLASS24 not found
10:40:16 String STR_ENH_DAMAGE_#GUNNERLIGHT not found
10:40:16 String STR_ENH_DAMAGE_#GUNNERLIGHT not found
10:40:16 String STR_ENH_DAMAGE_#COMMANDERLIGHT not found
10:40:16 String STR_ENH_DAMAGE_#COMMANDERLIGHT not found
10:40:16 String STR_ENH_DAMAGE_#COMMANDERLIGHT1 not found
10:40:16 String STR_ENH_DAMAGE_#RED1LIGHT not found
10:40:16 String STR_ENH_DAMAGE_#RED2LIGHT not found
10:40:22 String STR_ENH_DAMAGE_HITGLASS21 not found
10:40:22 String STR_ENH_DAMAGE_HITGLASS22 not found
10:40:22 String STR_ENH_DAMAGE_HITGLASS23 not found
10:40:22 String STR_ENH_DAMAGE_HITGLASS24 not found
10:40:22 String STR_ENH_DAMAGE_#GUNNERLIGHT not found
10:40:22 String STR_ENH_DAMAGE_#GUNNERLIGHT not found
10:40:22 String STR_ENH_DAMAGE_#COMMANDERLIGHT not found
10:40:22 String STR_ENH_DAMAGE_#COMMANDERLIGHT not found
10:40:22 String STR_ENH_DAMAGE_#COMMANDERLIGHT1 not found
10:40:22 String STR_ENH_DAMAGE_#RED1LIGHT not found
10:40:22 String STR_ENH_DAMAGE_#RED2LIGHT not found

**Comment by R3voA3** [comment]
These errors can be ignored for now. I'll fix them as soon as possible.

**Comment by R3voA3** [comment]
Error spawn will be fixed in next version.
