### ISSUE TITLE
ENH_featureTypeNew does not affect objects on server

### ISSUE THREAD

**Issue by IllidanS4** [R3voA3/3den-Enhanced#184]
Placing ENH_featureTypeNew on an object (resulting in `_this setFeatureType _value`) does not seem to work in some occasions on a dedicated server (works fine when the mission is run locally). Trying this on objects outside the map boundaries still results in them disappearing. However, putting `this setFeatureType 2;` manually in initialization does work, so perhaps the command is not run locally where it should be.

**Comment by R3voA3** [comment]
Interesting.  I will look into it. Thanks for your feedback.

**Comment by R3voA3** [comment]
https://github.com/R3voA3/3den-Enhanced/blob/c8d2055b4b3110bae61512b7900cbf417c2381fc/3denEnhanced/attributesObject/featureType.hpp#L7
Fixed
