### ISSUE TITLE
[Feature request] import/export scenario attributes manager 

### ISSUE THREAD

**Issue by tyl3r99** [R3voA3/3den-Enhanced#185]
Scenario Attributes Manager

An awesome tool!! Thank you. I was wondering if it's possible to have the ability to export and share these templates with other people. 

Thank you in advance revo great work as always

**Comment by R3voA3** [comment]
Thanks for the suggestion. I have decided to not implement that. It's too prone to errors. You can still share templates by creating a new mission, applying the template and sharing the mission.sqm.
