### ISSUE TITLE
[Feature request] inventory loadout manager (ACE arsenal compat)

### ISSUE THREAD

**Issue by tyl3r99** [R3voA3/3den-Enhanced#186]
In the inventory manager screen where you can search and very easily make a nice custom vanilla arsenal or storage box. 

It would be amazing if below the tick box for "is virtual" was another that said "is ace arsenal" 

A lot of people using ace really prefer that arsenal 
Again I appreciate everything you do here for the community 🙂

**Comment by R3voA3** [comment]
https://www.youtube.com/watch?v=arxh4xXdqL8

**Comment by tyl3r99** [comment]
Thank you!!
