### ISSUE TITLE
Manage available Zeus addons

### ISSUE THREAD

**Issue by R3voA3** [R3voA3/3den-Enhanced#193]
- [x] Exported string can be pasted into the "Manage Addons" module (Addons available can be different for each Zeus)
- [x] Add search
- [x] Add preview images to units inside addon
- [x] Display unit displayName instead of configName

- [x] Localisation

- [x] Wiki Update

**Comment by Eagle-Studios** [comment]
Would be nice to have some kinda way to manage indvidual ggame masters. i.e set it so that any actor zeus (Just there for RC and RPing), only have that ability, and cant place units etc

**Comment by ewbree** [comment]
Would be amazing, yes!
I am trying to make a Zeus scenario for the IFA3 addons on the maps. So it has to be entirely WW2 based. Disabling the default Arma 3 addons (e.g. NATO, CSAT, FIA and Altis/Stratis buildings and the like) would greatly help!
Maybe, if possible, make it also affect the arsenal in that same scenario.

**Comment by R3voA3** [comment]
https://youtu.be/AIGubDeTf6w
