### ISSUE TITLE
Broken Interface Preferences

### ISSUE THREAD

**Issue by ansin11** [R3voA3/3den-Enhanced#194]
Many (possibly all) of the options found under _Settings_ > _Preferences_ > _Interface_ > _Menu Strip Entries_ have no effect, even after restarting both the Editor and A3.

Issue encountered on A3 2.04 stable branch with only 3DEN Enhanced loaded after repairing the mod through the A3 launcher.

**Comment by R3voA3** [comment]
Thanks. Issue was found.

call ENH_fnc_removeItemsFromMenu; should be ENH_fnc_menuStrip_removeItems.
