### ISSUE TITLE
Mod is no longer dependency free

### ISSUE THREAD

**Issue by Tankbuster0** [R3voA3/3den-Enhanced#195]
Players report that they are required to have 3den enhanced to play the mission.

`	mods[]=
	{
		"3denEnhanced"
	};`
Is being added to the SQM

**Comment by R3voA3** [comment]
That is not true. mods[]= indicates that the mission was building using an editor mod and it is used to warn scenario creators if they open a mission without the mod it was created with. Mission can still be played without it.

**Comment by Tankbuster0** [comment]
Yes, you're right. Strange how this player, who I know to be otherwise reliable, got this error
