### ISSUE TITLE
Bug: Exporting mission as SQF no longer works.

### ISSUE THREAD

**Issue by L-McKendrick** [R3voA3/3den-Enhanced#198]
Reproducible with no other mods loaded.

Place any object or unit. Save mission and attempt to export as SQF. Game just prints error 

`!=# objects simulated
Generic error in expression`

This bug has been happening since the latest update.

**Comment by R3voA3** [comment]
Found the cause. It's a BI bug. Ticket is up https://feedback.bistudio.com/T158949

I am gonna remove the attribute which causes that temporarily. Thanks again for the report.

**Comment by R3voA3** [comment]
I've just pushed an updated which removes the attribute which causes this temporarily until the issue is fixed in Arma 3.
