### ISSUE TITLE
Translation Widget

### ISSUE THREAD

**Issue by beno83au** [R3voA3/3den-Enhanced#211]
Hi Revo. Myself, Gunter and Johnny have posted about some annoyances with 3den when it comes to moving rotated objects here:
[BI Forum](https://forums.bohemia.net/forums/topic/234975-lock-object-transformation-coordinates/?tab=comments#comment-3440361)

In short, rotating an object on any of it's axis then clicking and dragging to move it resets the rotations (orientates to sea). Currently, the only way to preserve the rotations is to use the translation widget to drag the object into a new position, albeit along only one axis at a time. So, is there a way for 3den Enhanced to prevent this auto-snapping/resetting of rotations when moving?

Thanks.

**Comment by R3voA3** [comment]
Hey, thanks for the suggestion. I'll look into it and see if I can do something. No promise though! I'll keep you posted.

**Comment by R3voA3** [comment]
https://feedback.bistudio.com/T159275 
I've created a ticket and also contacted the devs. Perhaps there is a chance to get it fixed in engine.

**Comment by R3voA3** [comment]
Gonna close this since dedmen took over.
