### ISSUE TITLE
Add weight indicator to VIM

### ISSUE THREAD

**Issue by klausman** [R3voA3/3den-Enhanced#212]
This would be especially useful to see whether placed boxes with kit would still be draggable/carryable with ACE.

Actually getting the limits for that from ACE is possible (they default to 600/800), but just seeing the number of the current state (box plus its contents) would be very helpful already.

**Comment by R3voA3** [comment]
Does ace modify the weight value of items? If yes, than this would be pretty inaccurate.

**Comment by klausman** [comment]
> Does ace modify the weight value of items? If yes, than this would be pretty inaccurate.

Probably, at least for some. There is this function:

https://github.com/acemod/ACE3/blob/master/addons/dragging/functions/fnc_getWeight.sqf

that is used to make the decision for dragging/carrying weights. Maybe if ACE3 is detected by 3E, it could use that function? Not sure if that special-casing is in scope for you.

**Comment by R3voA3** [comment]
I checked if this is doable, but the weight can only easily be checked during the Scenario. Adding this functionality now inside the UI will mean I have to rewrite quite a few things which I don't have the time for anymore.

**Comment by klausman** [comment]
Thanks for considering it!
