### ISSUE TITLE
Can't configure SP Respawn System

### ISSUE THREAD

**Issue by maxvas007** [R3voA3/3den-Enhanced#216]
My soldiers just have not "Single Player Respawn" property in Attributes. What I did wrong?

**Comment by R3voA3** [comment]
![20210710100153_1](https://user-images.githubusercontent.com/17484252/125156472-e4b5d380-e165-11eb-898b-3c21d066f27d.jpg)

You don't have this?

**Comment by maxvas007** [comment]
> ![20210710100153_1](https://user-images.githubusercontent.com/17484252/125156472-e4b5d380-e165-11eb-898b-3c21d066f27d.jpg)
> 
> You don't have this?

No, I have, and even tried to set 10 tickets, but, still, no respawning after death. "Only units with Single Player Respawn enabled in their attributes are affected.": I have not this exactly, though in YouTube video - guy has "Single Player Respawn" under "Disable Deletion on Death". Multiplayer respawn system works correctly, when I launching scenario through MP mode, but SP... :-( I'm playing in Editor, by the way, by "Playing as this character". Tried to start mission by "Play Singleplayer Scenario" too.

**Comment by R3voA3** [comment]
There might have been a bug in the past versions which causes this issue which I believe I have fixed now.
