### ISSUE TITLE
Broken Interface Preferences

### ISSUE THREAD

**Issue by ansin11** [R3voA3/3den-Enhanced#226]
I discovered another problem with the options found under _Settings_ > _Preferences_ > _Interface_:
1. Start A3 with 3DEN Enhanced, go to the Editor, change one of the interface preferences from _Collapse Entity List on Start_ to _Show Entity Counter_ and confirm with OK.
2. Close A3, restart it and go to the Editor, this time without 3DEN Enhanced.
3. Close A3, restart it and go to the Editor again, now with 3DEN Enhanced loaded. The preferences have now reset to the 3DEN Enhanced default settings.

I also noticed that there are checkboxes without corresponding descriptions under _Settings_ > _Preferences_ > _Interface_ > _Menu Strip Entries_, specifically between the _Variable Viewer_ and _Log Game Info_ entries as well as between the _Create Trigger (Whole Map Coverage)_ and _Community Wiki_ entries.

**Comment by R3voA3** [comment]
Thanks for the report. I'll look into it.

**Comment by R3voA3** [comment]
1 & 2 - Probably an Arma bug
3 - Should be fixed
