### ISSUE TITLE
Missing ")" in ENH_groupMarker CustomAttribute

### ISSUE THREAD

**Issue by hypoxia125** [R3voA3/3den-Enhanced#229]
### Description

When using the group marker system, a missing ")" error is thrown. Browsing through the .SQM it looks like your custom class attribute under expression is missing a ")" in the first condition of the code.

```sqf
if (!is3DEN && (_value # 0 != '') then {  //THE ERROR IS ON THIS LINE
    [_this, _value] spawn {
        scriptName 'ENH_Attribute_groupMarker';
        params ['_group', '_value']; _value params ['_type', '_color', '_text', '_showgroupsize']; private _leader = leader _group; private _marker = createMarker [ format ['ENH_groupMarker_%1', str _group], _leader ]; _marker setMarkertype _type; _marker setMarkerColor _color; _marker setMarkertext (_text call BIS_fnc_localize); while {true} do {
            sleep 1;
            if (units _group isEqualto []) exitwith {
                deleteMarker _marker
            };
            if (_group getVariable ['ENH_groupMarker_Update', true]) then {
                _marker setMarkerPos _leader;
                if (_showgroupsize) then {
                    _marker setMarkertext format ['%1 (%2)', groupid _group, count units _group];
                };
            };
        };
    };
};
```

### Steps To Reproduce

1. Enable the group marker system and set arguments
2. Notice the error when you click confirm on the group attribute menu
3. Open .SQM and search for "ENH_groupMarker"
4. Notice the missing ")" in the expression attribute

### Expected behavior

The first conditional is an error which will harm the rest of the script.

### 3den Enhanced Version

July 20th 2021

### Arma 3 Version

204,147719 "STABLE"

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by hypoxia125** [comment]
I see in groupMarker.hpp it has the correct amount of parenthesis so I'm not sure what's going wrong with the translation to the .sqm

```hpp
      expression = "\
      if (!is3DEN && (_value # 0 != '')) then\
      {\
        [_this, _value] spawn\
        {\
          scriptName 'ENH_Attribute_GroupMarker';\
          params ['_group', '_parameters'];\
          _parameters params ['_type', '_color', '_text', '_showGroupSize'];\
          private _leader = leader _group;\
          private _marker = createMarkerLocal\
```

**Comment by R3voA3** [comment]
> I see in groupMarker.hpp it has the correct amount of parenthesis so I'm not sure what's going wrong with the translation to the .sqm
> 
> ```c++
>       expression = "\
>       if (!is3DEN && (_value # 0 != '')) then\
>       {\
>         [_this, _value] spawn\
>         {\
>           scriptName 'ENH_Attribute_GroupMarker';\
>           params ['_group', '_parameters'];\
>           _parameters params ['_type', '_color', '_text', '_showGroupSize'];\
>           private _leader = leader _group;\
>           private _marker = createMarkerLocal\
> ```

Because the issue has already been fixed ;) Thanks for the bug report though, much appreciated!

**Comment by shukari** [comment]
In the current workshop mod the groupMarker.hpp is:
`if (!is3DEN && (_value # 0 != '') then\`

Full file:
```
class ENH_GroupMarker
{
  displayName = "$STR_ENH_GROUPMARKER_DISPLAYNAME";
  collapsed = 1;
  class Attributes
  {
    class ENH_GroupMarker_Subcategory
    {
      description = "$STR_ENH_GROUPMARKER_DESCRIPTION";
      data = "AttributeSystemSubcategory";
      control = "ENH_SubCategoryNoHeader3_Fixed";
    };
    class ENH_GroupMarker
    {
      displayName = "$STR_ENH_GROUPMARKER_DISPLAYNAME";
      tooltip = "$STR_ENH_GROUPMARKER_DESCRIPTION";
      property = "ENH_groupMarker";
      control = "ENH_GroupMarker";
      expression = "\
      if (!is3DEN && (_value # 0 != '') then\
      {\
        [_this, _value] spawn\
        {\
          scriptName 'ENH_Attribute_GroupMarker';\
          params ['_group', '_value'];\
          _value params ['_type', '_color', '_text', '_showGroupSize'];\
          private _leader = leader _group;\
          private _marker = createMarker\
          [\
            format ['ENH_GroupMarker_%1', str _group],\
            _leader\
          ];\
          _marker setMarkerType _type;\
          _marker setMarkerColor _color;\
          _marker setMarkerText (_text call BIS_fnc_localize);\
          while {true} do\
          {\
            sleep 1;\
            if (units _group isEqualTo []) exitWith {deleteMarker _marker};\
            if (_group getVariable ['ENH_GroupMarker_Update', true]) then\
            {\
              _marker setMarkerPos _leader;\
              if (_showGroupSize) then\
              {\
                _marker setMarkerText format ['%1 (%2)', groupId _group, count units _group];\
              };\
            };\
          };\
        };\
      };";
      defaultValue = "['', [side _this, true] call BIS_fnc_sideColor, groupID _this, true]";
    };
  };
};
```

**Comment by R3voA3** [comment]
Thanks for the report @shukari. The issue has been fixed internally and I am going to release an update as soon as Arma 3 v2.06 gets released.

**Comment by shukari** [comment]
OK, check. Thank you!
