### ISSUE TITLE
Vehicle Inventory Manager: Unable to increase amount of pre-existing items

### ISSUE THREAD

**Issue by Zantza** [R3voA3/3den-Enhanced#247]
### Description

When a crate with items already in it is spawned, pressing right arrow key or Inventory-->+1 on the items does nothing. Removing the items does work.

New items can be added. After adding a new item and then trying to increase the amount of an item that was already in the inventory, it instead increases the amount of the item you just added.

### Steps To Reproduce

1. Spawn a crate in 3den (for example "Basic Ammo [AAF]")
2. Open VIM
3. Try to add more of the items that are already inside

### Expected behavior

Amount should increase

### 3den Enhanced Version

v6.5

### Arma 3 Version

2.06

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by R3voA3** [comment]
Thanks for the report.

**Comment by R3voA3** [comment]
I am unable to reproduce that.

https://youtu.be/1QzKjl5W0co

**Comment by Zantza** [comment]
Ah, my bad. Didn't realise you had to select the item also in the left panel. It would be nice if you could simply add stuff by only selecting in the right panel.

**Comment by R3voA3** [comment]
Thanks for the suggestion. I'll put it on my to-do.
