### ISSUE TITLE
ENH_featureTypeNew does not work

### ISSUE THREAD

**Issue by IllidanS4** [R3voA3/3den-Enhanced#249]
### Description

The visibility settings on objects does not work; it doesn't affect the object's parameters since `setFeatureType` is called improperly.

### Steps To Reproduce

1. Create a object in editor.
2. Go into attributes, change the visibility to terrain.
3. Create another object but put `this setFeatureType 2` in initialization.
4. Launch the mission; only the second object will have the adjusted visibility.

### Expected behavior

It seems `_value remoteExec ['setFeatureType', 0, _this]` as is set by the attribute is not correct. The function is called like `object setFeatureType type`, so, based on how `remoteExec` works, it should be `[_this, _value] remoteExec ['setFeatureType', 0, _this]`.

However, I am not quite sure why `remoteExec` would be even necessary. Since the initialization is performed by every client anyway, this would just result in the function being propagated from every client to every other client, unnecessarily. Unless JIP is required, but the initialization would be called for JIP clients anyway.

### 3den Enhanced Version

v6.6

### Arma 3 Version

v2.06

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by R3voA3** [comment]
Thanks for the detailed report. I'll look into it.
