### ISSUE TITLE
3den Autosave failed

### ISSUE THREAD

**Issue by KeiwaM** [R3voA3/3den-Enhanced#253]
### Description

Today I was editing a mission that my squad is gonna play. I saved about an hour in and after that, I got regular autosaves. I both saw it autosave and I heard the noise it makes. 2 hours after the save I did, the editor crashed after I tabbed out by accident. When I load the game up again, the only save is the one I had 2 hours ago. It had saved none of the autosaves to the file and I lost 2 hours worth of progress.

### Steps To Reproduce

N/A

### Expected behavior

Autosave should have either saved to the file itself or made a backup autosave to recover.

### 3den Enhanced Version

v7.5.1

### Arma 3 Version

v2.08.149102

### Is the issue reproduceable?

- [ ] Always
- [ ] Sometimes
- [X] Only once

### Game breaking?

- [X] Yes, it is
- [ ] No, it isn't

### Relevant Assets

Can't find logfile

**Comment by R3voA3** [comment]
Hello, thanks for the report.

3den Enhanced does not modifiy autosave behavour in any way.
