### ISSUE TITLE
New Local Only State bugged

### ISSUE THREAD

**Issue by Hexomanya** [R3voA3/3den-Enhanced#254]
### Description

The new "Local Only" state does not show up in the menu correctly. Even if you get it show up it does not mark the object as local only.

### Steps To Reproduce

1. Start Arma only with 3den-Enhanced loaded
2. Go in Editor. Altis was used.
3. Place down an object. E.g. HMS Proteus
4. Now the Local Only state will not show up correctly. (Problem 1)
5. Make it a simple Object and press ok
6. Reopen the object. Local only state should now be available.

=> If you make it a local only & simple object, local only will stay but object icon will stay the same color.
=> If you make it local only and not simple object the local only state will be invisible again after closing. Object icon color will stay the same (changes in vanilla)

### Expected behavior

Local only state should always be visible. Object icon color will change with the state.

### 3den Enhanced Version

v6.2

### Arma 3 Version

v2.10

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by R3voA3** [comment]
Hello, thanks for your feedback. The new local only attribute is a vanilla Arma 3 attribute added with the lastes 2.10 update. Head to the Arma 3 Feedback Tracker if you encounter any issues with it.
