### ISSUE TITLE
Filename instead of manually set name in Eden is shown in multiplayer mission selection menu on missions saved with 3den-Enhanced

### ISSUE THREAD

**Issue by Qerbas** [R3voA3/3den-Enhanced#255]
### Description

Whenever a mission is saved with 3den, even if you adjust none of the custom paramaters, the mission will show up in the multiplayer mission selection menu as it's filename, instead of the name you set in the 3den editor. If the mission name is set in description.ext it works normally.

### Steps To Reproduce

1. Load only 3den-Enhanced
2. Create mission with any filename for example on Stratis: "mission.Stratis"
3. Name it whatever you want (for example "My really great mission")  under Attributes->General->Title and then save it
4. Export the mission to multiplayer and load the mission on a local host or dedicated server and notice how it's called "mission.Stratis" instead of "My really great mission" in the mission selection menu.  It will show the proper name once you're in the lobby/in game

### Expected behavior

The mission should show up as the name you set in as the title, not the filename.

I've attached 3missions demonstrating this: "A_notshowingthecorrectname.Altis" will show whatever the filename's called in the mission select screen,  "showingthecorrectname.Altis" will show up as "An even better mission", and "alsoshowingthecorrectname.Altis" will show up as "A mission that is superior".  

They are all identical except the first one is saved with 3den, the second one isn't, and the third one is saved with 3den but a description.ext is added with the a set briefing name

### 3den Enhanced Version

v7.6.2

### Arma 3 Version

v2.10

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

### Relevant Assets

[example missions.zip](https://github.com/R3voA3/3den-Enhanced/files/9690834/example.missions.zip)

**Comment by R3voA3** [comment]
Firstly, thanks for that great issue report.

Unfortunately, this is an Arma 3 issue. In the mission selection screen, the mission.sqm does not get parsed but only the description.ext. That's why the name set in mission.sqm via the attributes won't be recognized until the mission is actually loaded (in the lobby).

**Comment by Qerbas** [comment]
But as I've shown, setting the name in attributes does in fact work without 3den Enhanced, you can test this yourself.  How come it only breaks when the mission is saved with 3den Enhanced loaded?

**Comment by R3voA3** [comment]
I did a bit of research and there seems to be an issue with the number of attributes that read. Since 3den Enhanced adds new attributes the limit is reached. I'll investigate further.

**Comment by R3voA3** [comment]
Engine bug.
