### ISSUE TITLE
ENH_AI needs a reset button

### ISSUE THREAD

**Issue by hypoxia125** [R3voA3/3den-Enhanced#259]
### Description

Currently, if you touch the sliders under the AI skill settings that ENH_AI custom attribute provides, there is no way to reset them without deleting the group/ completely. If it applies to one unit (say the squad leader) and you delete that squad leader, the attributes will move to the next leader (verified by looking at mission.sqm). The only way to reset it is to delete the whole group.

### Steps To Reproduce

// Verify control
1. Place down group in editor
2. Set Vanilla Arma's skill slider to 100% in group attribute menu
3. Save
4. Start Mission
5. Check skills of units using `skill` (they should all return `1`)

// Test
1. Place down group in editor
2. Set Vanilla Arma's skill slider to 100% in group attribute menu
3. Mess with the sliders under ENH_AI skill settings
4. Save
5. Reset the sliders back to 50%
6. Save
7. Start Mission
8. Check skills of units using `skill` (they should all return `1` but instead they return `0.5`) // needs a reset button

### Expected behavior

See above in steps to reproduce

### 3den Enhanced Version

Feb 2nd 2023

### Arma 3 Version

Launcher version: 1.5.150316  Game version: 2.12.150301

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by R3voA3** [comment]
As an alternative I could add a tool to the menu strip to reset AI skill of all selected entities.
