### ISSUE TITLE
Terrain texture changes after coming back from preview (Need more info)

### ISSUE THREAD

**Issue by Carbonian1** [R3voA3/3den-Enhanced#270]
### Description

Whenever opening the map after playing a mission in the Eden editor the green foliage indicator will disappear. Can be fixed by looking at another area on the map without seeing the problem area and then going back but it is a bit annoying.

### Steps To Reproduce

1. Play mission in Eden Editor
2. End the mission
3. Open map and check area where the map initially starts for green foliage mark.

### Expected behavior

I expected the map to be completely normal.

### 3den Enhanced Version

Latest Version (Could not find exact version in files, but I uninstalled then reinstalled)

### Arma 3 Version

v2.12

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by Carbonian1** [comment]
Well, I tried to replicate it as I have done before and it doesn't seem to do it. I'll be sure to send a screenshot if I can manage to replicate it, but I'm not so sure anymore. Might have just have been my Arma 3 files. Sorry for the trouble.

**Comment by R3voA3** [comment]
No problem. I'll keep this ticket open. If you get some more information feel free to add them here.
