### ISSUE TITLE
Missing string for "STR_ENH_TOOLS_LIMIT_ARSENAL..."

### ISSUE THREAD

**Issue by genjonakasone** [R3voA3/3den-Enhanced#274]
### Description

In current version of 3den Enhanced an option for limiting arsenal (and title of its window) in Tools -> Loadout Tools is missing its actual text and the string classname is displayed instead.

### Expected behavior

Display text instead of a class.

### 3den Enhanced Version

v7.7.8

### Arma 3 Version

v2.12

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by linkion** [comment]
It was fixed and merged in https://github.com/R3voA3/3den-Enhanced/pull/269. Steam workshop mod will be updated soon. Though since the limited arsenal is experimental, it may disappear.

**Comment by R3voA3** [comment]
Thanks for your report. 

As this has been fixed internally already I will close the ticket.
