### ISSUE TITLE
Placement Tools Hotkey and Buttons Disappeared

### ISSUE THREAD

**Issue by CodenameAter** [R3voA3/3den-Enhanced#276]
### Description

First, the hotkey no longer works. Secondly, the buttons related to where the tool is centred are no longer present. Finally, none of the other options exist anymore related to the patterns and so forth. I am not sure if this is a conflict, but it has only happened since the update.

![image](https://github.com/R3voA3/3den-Enhanced/assets/84730219/47c0aa8f-2a28-4c23-a7e8-98d5d48c6c6b)

### Steps To Reproduce

1. Open Placement Tools
2. There is no button

### Expected behavior

The hotkey used to work and there used to be buttons to select different options, as well as a icon showing the location.

### 3den Enhanced Version

7.7.9

### Arma 3 Version

Hotfix 2.14

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by R3voA3** [comment]
Thanks for the report. I'll fix that with the next update.
