### ISSUE TITLE
Object right click copy class name to clipboard

### ISSUE THREAD

**Issue by mwpowellhtx** [R3voA3/3den-Enhanced#283]
### Description

Would be great to be able to copy the class name for a selected object to clipboard, say in the right click menu.

### Use-Cases

More easily copy the class name to the clipboard. Versus having to wait long periods for the config viewer.

**Comment by R3voA3** [comment]
Thanks for the suggestion. Does none of the following options does what you need?

![20230924163833_1](https://github.com/R3voA3/3den-Enhanced/assets/17484252/d8147f70-bda6-4bda-8976-66f21a9299e9)

**Comment by mwpowellhtx** [comment]
Perhaps, was not aware. I'll have a look, thank you...

**Comment by mwpowellhtx** [comment]
👍 `"Log Classes to Clipboard"`, although should probably be named instead `"Log Class to Clipboard"` or even, `"Log Object Class to Clipboard"` if you wanted to be more precise.

Along similar lines, `"Log Classes as String to Clipboard"`, not sure it adds much value, TBH, most editors these days know how to open-close special characters like quotation marks, can paste the first one in, easy peazy.

I see the `"Log Object Info"`, that's a good one. Might add a `"Log Object Class Hierarchy to Clipboard"`.

Although I see now it also works for multiple-object selections. So, probably, appropriately named.

FWIW, thanks!
