### ISSUE TITLE
Q: About saving missions in prep for PBO packaging

### ISSUE THREAD

**Issue by mwpowellhtx** [R3voA3/3den-Enhanced#286]
### Description

Started off editing mission files with hundred percent mod coverage, including _3DEN_. Now that I am satisfied with the mission state, I am looking to strip out the mods, re-save, and get set for packaging to PBO.

### Use-Cases

Did as I described above, zero mods loaded, went to edit one such mission, was immediately prompted, and in a couple of instances, with the following warnings about custom attributes, not being able to edit and save them, etc. Prompted with this message in a couple of instances, as well as before and after the customary force load prompt.

What I need to identify are the basest set possible of mods that I can load and be _"okay"_, save, package, then, ostensibly, be able to load up a server with the desired mod set.

What I don't know is the extent to which this is impactful, requiring of _3DENENHANCED_.

### Relevant Assets

Getting the following error message pop up editing with all mods stripped out.

![image](https://github.com/R3voA3/3den-Enhanced/assets/1824187/6ea2fd08-90de-4f90-b526-d995de87427f)

**Comment by R3voA3** [comment]
Hello,

it's quite easy with 3den Enhanced. If you haven't used any custom attribute from this mod then you can ignore this warning as no additional data was written to the mission.sqm anyway. 

If you are not sure if you have used any custom attributes, open the mission.sqm and search for "ENH_"

If there are no search results you don't need the mod when saving the mission.

Does this answer your question?

**Comment by mwpowellhtx** [comment]
Possibly, I'll check it out, thank you. I did place a couple of 'static' objects, with special states, basically invisible objects, still providing area effect options, ammo sources and such, below carrier decks. I think possibly these are the objects being detected, but that is TBD. Will let you know, thank you, sir.

**Comment by R3voA3** [comment]
The message shown has nothing to do with the objects being placed in the scenario.

3den Enhanced simply creates an entry in the mission.sqm that it was used to edit the scenario. That's why it shows the warning if you edit the scenario without it.

The message will even show for an empty scenario if it was just saved with 3den Enhanced loaded.

**Comment by mwpowellhtx** [comment]
Yep I do see the editor info class. Need to verify a bit, play test, so far so good editor wise anyway.
