### ISSUE TITLE
3den enhanced Establishing Shot is no longer functioning properly on mission files that had it loaded before after recent update

### ISSUE THREAD

**Issue by ZarloSkald** [R3voA3/3den-Enhanced#288]
### Description

I play 3den enhanced in all my missions, but there is not any mod conflict that causes the issue. The missions that have the mods loaded dont work with the establishing shot; all that happens is the effect overlays from your character's pov camera, and not the actual aerial shot. This works in new missions and with the mods loaded, but only in previous previous missions does it not function correctly.  This only happened after the recent (oct 9th) update, and was not an issue the day before before. Resetting the values and turning it off, repairing all mods, and such do not change anything. 

### Steps To Reproduce

1. Go load any world/mission created before the most recent update (other mods or not) 
2. load the mission either in multiplayer or singleplayer

### Expected behavior

The effect of the uav style establishing shot will play, along with the sound, but you'll still just be in first person pov with the effect playing overtop. This only happens on missions created before the most recent update (oct 9th)

### 3den Enhanced Version

v7.8.3

### Arma 3 Version

v2.14.150957

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by ZarloSkald** [comment]
Resetting did not help either

**Comment by R3voA3** [comment]
Thanks for the report. Going to check what's causing it today.

**Comment by ZarloSkald** [comment]
> Thanks for the report. Going to check what's causing it today.

Thank you so much... It made me so frustrated because nothing I did could fix it

**Comment by R3voA3** [comment]
> > Thanks for the report. Going to check what's causing it today.
> 
> Thank you so much... It made me so frustrated because nothing I did could fix it

I was unable to reproduce the issue. I tried with a new mission and one that is 5 years old. 

Can you upload the mission here where you have the issue? Mission.sqm is enough.

**Comment by ZarloSkald** [comment]
> Mission.sqm

How would I do that? I am not very well versed with the game's more code oriented things

**Comment by ZarloSkald** [comment]
github says it doesn't support sqm files ... what should I do instead? zip file?

**Comment by ZarloSkald** [comment]
> > > Thanks for the report. Going to check what's causing it today.
> > 
> > 
> > Thank you so much... It made me so frustrated because nothing I did could fix it
> 
> I was unable to reproduce the issue. I tried with a new mission and one that is 5 years old.
> 
> Can you upload the mission here where you have the issue? Mission.sqm is enough.

I posted it in a previous reply

**Comment by ZarloSkald** [comment]
> > > Thanks for the report. Going to check what's causing it today.
> > 
> > 
> > Thank you so much... It made me so frustrated because nothing I did could fix it
> 
> I was unable to reproduce the issue. I tried with a new mission and one that is 5 years old.
> 
> Can you upload the mission here where you have the issue? Mission.sqm is enough.

I have been able to figure out what may be the problem, though I receive no issues or alerts to any conflictions or issues with mods on load, the TTS cloak mod, and any mission I have used it in; this was not an issue that happened before 3den enhanced was updated on the 9th, and for some reason didn't seem to be caught by me during a sweep of all mods one by one. It is rather odd, but I am glad I found the potential culprit. I don't know if I should contact THAT mod's creator or not about this, but I feel like it's worth the knowledge

**Comment by R3voA3** [comment]
Glad you found out which mod is causing it.

I'll test later if the TTS Mod breaks the default Arma 3 function as well.

If that's the case then it might be worth contacting the author.

**Comment by ZarloSkald** [comment]
> Glad you found out which mod is causing it.
> 
> I'll test later if the TTS Mod breaks the default Arma 3 function as well.
> 
> If that's the case then it might be worth contacting the author.

The issue persists....
