### ISSUE TITLE
Make backup (sqm) location configurable

### ISSUE THREAD

**Issue by klausman** [R3voA3/3den-Enhanced#295]
### Description

At the moment, the mission backups are saved to the mission folder itself. This has the downside that when hand-packing the mission (e.g. using 7zip to pack the folder for someone else, or using PBO Explorer to make a shippable PBO with version numbering), one has to hand exclude the backups somehow. Since I never use the ingame way of making PBOs, I don't know if it happens there as well. If I don't do this a typical mission I have worked on for a while will be 20+M instead of just 4M, which means players/clients download 16M of pointless data.

### Use-Cases

see above, packing missions.

**Comment by R3voA3** [comment]
I cannot store them outside of the scenario folder. Just delete the backup folder prior to packing or move it somewhere else.

**Comment by klausman** [comment]
> I cannot store them outside of the scenario folder. Just delete the backup folder prior to packing or move it somewhere else.

My above PR proves that this isn't the case: Pythia will happily copy the sqm to wherever the user can write.

**Comment by R3voA3** [comment]
> > I cannot store them outside of the scenario folder. Just delete the backup folder prior to packing or move it somewhere else.
> 
> My above PR proves that this isn't the case: Pythia will happily copy the sqm to wherever the user can write.

Yeah. You are right.

I'll review the code tomorrow and add the translation
