### ISSUE TITLE
Establishing Shot

### ISSUE THREAD

**Issue by 6komodo6** [R3voA3/3den-Enhanced#298]
### Description

Copied location in the map and put it in the Establishing Shot section but when I hit play it reverts to POV from the player and no UAV shot is made

### Expected behavior

UAV shot at the start

### 3den Enhanced Version

7.8.8

### Arma 3 Version

2.14

### Is the issue reproduceable?

- [X] Always
- [ ] Sometimes
- [ ] Only once

### Game breaking?

- [ ] Yes, it is
- [X] No, it isn't

**Comment by R3voA3** [comment]
I cannot reproduce that. Works as expected.

I remember some mod conflict caused that but don't remember which mod it was.

**Comment by 6komodo6** [comment]
i see, i'll try to check it with one mod at a time
