### ISSUE TITLE
ESE not showing items

### ISSUE THREAD

**Issue by Pixelated-Grunt** [R3voA3/3den-Enhanced#305]
Hi there,

I've added an import function from clipboard into ESE inventory. However, I'm not 100% sure if I've branch off correctly since I couldn't find any releases or tags.

The code is based on [commit 3c5c0ab](https://github.com/R3voA3/3den-Enhanced/tree/3c5c0ab896e86afc780c7482586c6b0029349956). I tried to match the date from Steam release. Please let me know if I should submit a PR or should use another code base for it.

Cheers,

Screenshot:
![20240822041255_1](https://github.com/user-attachments/assets/454d066d-3364-47ef-ad21-e1f5ae0b941d)

**Comment by R3voA3** [comment]
Thanks.

Just create a merge request. I'll handle anything else.

**Comment by R3voA3** [comment]
Seems like ESE is no longer working for me. Could you compare the current master branch with your changes to check if you see something obvious?

**Comment by Pixelated-Grunt** [comment]
Sure will do.

**Comment by Pixelated-Grunt** [comment]
PR sent. Screenshot from current master with import from clipboard function.

![20240823232548_1](https://github.com/user-attachments/assets/42425a82-1e6a-4113-8d20-3a2331886102)

**Comment by R3voA3** [comment]
Great. Seems fixed. Thanks a lot!
