### ISSUE TITLE
Variable naming tool doesn't work.

### ISSUE THREAD

**Issue by Bragg-O** [R3voA3/3den-Enhanced#343]
I've encountered an issue with the Variable Naming Tool. When pressing ALT + N, the interface to add variable names to all selected objects appears as expected. However, when executing the process, nothing happens at all.

**Comment by BlackbirdAter** [comment]
I can also confirm I am having the exact same issue. This appears to have started after the last update.

**Comment by R3voA3** [comment]
Thanks for reporting. This has already been fixed internally.

Feel free to use the previous version from here https://github.com/R3voA3/3den-Enhanced/tree/master/releases until the next update.
