### ISSUE TITLE
Feature request: Add a shortcut that open the unit's ACE Arsenal 

### ISSUE THREAD

**Issue by 6komodo6** [R3voA3/3den-Enhanced#349]
If ACE is loaded, can you add a keyboard shortcut that open the selected unit's ACE arsenal instantly?
Maybe a CBA setting that can adjust what that shortcut is.

Ty.

**Comment by R3voA3** [comment]
This has been implemented.

**Comment by 6komodo6** [comment]
I didn't know that, what's the kb shortcut?

**Comment by 6komodo6** [comment]
Hi R3vo
what's the kb shortcut for it?

**Comment by 6komodo6** [comment]
To be implemented i see, ty
