### ISSUE TITLE
Dynamic AI Skill Settings can increase past max set parameters

### ISSUE THREAD

**Issue by Vorkal** [R3voA3/3den-Enhanced#78]
I think I've spotted a problem with the Dynamic AI Skill Settings option under the Multiplayer tab. But the problem is BIS_fnc_EXP_camp_setSkill's fault. 

That attribute calls on `BIS_fnc_EXP_camp_dynamicAISkill`. Which uses the BI setSkill function.

from BIS_fnc_EXP_camp_setSkill:
// Lerp function
private _fn_lerp =
{
	params [["_a", 0.0, [0.0]], ["_b", 0.0, [0.0]], ["_alpha", 0.0, [0.0]]];
	_a + _alpha * (_b - _a);
};

private _alpha = count ([] call BIS_fnc_listPlayers) / MAX_PLAYERS;
private _skill = [_skillMin, _skillMax, _alpha] call _fn_lerp;
private _skillAim = [_skillAimMin, _skillAimMax, _alpha] call _fn_lerp;

`MAX_PLAYERS` is included from \A3\Missions_F_Exp\Campaign\commonDefines.inc and is 4. The max players in the Apex Campaign.
So if the amount of players in someone's mission is above 4 players, the `_alpha` will be greater than 1, which will cause lerp to break out past the max parameters. 

I ran this with 5 clients on a server (Vanilla) just to double check:
`[east,0.1,0.2,0.7,0.6] call BIS_fnc_EXP_camp_setSkill;`

and got:
`23:22:44 "417/BIS_fnc_log: [BIS_fnc_EXP_camp_setSkill] Skill set for side EAST - Alpha: 1.25 / Skill: 0.85 / SkillAim: 0.7"`

same thing occurs when setting it through 3den Enhanced

`1:13:56 "417/BIS_fnc_log: [BIS_fnc_EXP_camp_setSkill] Skill set for side WEST - Alpha: 1.25 / Skill: 0.25 / SkillAim: 0.425"
 1:13:56 "417/BIS_fnc_log: [BIS_fnc_EXP_camp_setSkill] Skill set for side EAST - Alpha: 1.25 / Skill: 0.25 / SkillAim: 0.425"
 1:13:56 "417/BIS_fnc_log: [BIS_fnc_EXP_camp_setSkill] Skill set for side GUER - Alpha: 1.25 / Skill: 0.25 / SkillAim: 0.425"`

So it looks like the author didn't intend for the function to be used outside of APEX.
This could be solved with something like this, but would require making two new functions just to replace that problematic code: 

//Find playable slots on all sides.
private _maxPlayers = 0;
{
	//add playableSlots count to _maxPlayers
	_maxPlayers = _maxPlayers + playableSlotsNumber _x;
} forEach [west,east,independent,civilian];

private _alpha = count ([] call BIS_fnc_listPlayers) / _maxPlayers; 
if (_alpha > 1) then {_alpha = 1};

Or just make the attribute not fire if more than 4 player slots are available. Which would be much easier.

**Comment by R3voA3** [comment]
Thanks for that detailed report. I'll see if I can fix it, or inform BI about the problem.

**Comment by R3voA3** [comment]
https://forums.bohemia.net/forums/topic/143930-general-discussion-dev-branch/?do=findComment&comment=3394100

**Comment by R3voA3** [comment]
I will not fix this since it's using a vanilla function.
