### ISSUE TITLE
Automatic adding of Hold Action

### ISSUE THREAD

**Issue by SchwererKonigstiger** [R3voA3/3den-Enhanced#84]
Opening any object's attributes with 3den Enhanced loaded will append a Custom Attribute to the object, whether or not that object actually needs to have a Hold Action or not. This increases the size of the mission.sqm files massively, pushing a 700kb mission to be upwards of 3.3mb whilst unbinned.
Binning missions does make the file size smaller, but this is still an issue.
Note that opening the attributes of many objects at once (to say, set simple objects for a large base, for example), will add the `ENH_Hold_Action` to _each and every one_ of these objects.

Rather than attempting to paste one of the custom attributes, I have provided a mission.sqm (as a text file)  that is affected by this issue.

[mission.sqm](https://github.com/R3voA3/3den-Enhanced/files/4113691/mission.txt)

**Comment by R3voA3** [comment]
Thanks for your report. I've already known what's causing it, but I have not yet found a solution.

**Comment by dedmen** [comment]
How about storing the default value in a global variable, that Eden enhanced sets once somehow?
Maybe there is some way to add a mission attribute that will always execute before the other ones, that can set variables?

**Comment by R3voA3** [comment]
@dedmen Thanks for your suggestion. 
@SchwererKonigstiger Thanks for reporting the issue.

If have fixed the issue with a bit of a workaround by exiting the save function with the exact default value set in the attribute config. 6090dc5ee45b7d0195a984fa76fa3967ffce7b24 2a44609

**Comment by SchwererKonigstiger** [comment]
Whelp, it can be manually trimmed out of old missions (with some effort), but other than that this is great!
Looking forward to an updated release.

**Comment by R3voA3** [comment]
> Whelp, it can be manually trimmed out of old missions (with some effort), but other than that this is great!
> Looking forward to an updated release.

Yeah, it's a bummer it stays in the mission.sqm, but that seems to be that case for all attributes, even the vanilla ones.

**Comment by R3voA3** [comment]
Fixed

**Comment by lkvk** [comment]
Issue still exists, opening and closing object attributes leads to `ENH_HoldAction` attribute getting added.

**Comment by R3voA3** [comment]
I found the issue and applied a fix. Thanks for pointing that out.

**Comment by R3voA3** [comment]
Fixed
