### ISSUE TITLE
ENH_doStop causes playable characters to spawn as seagulls

### ISSUE THREAD

**Issue by IllidanS4** [R3voA3/3den-Enhanced#85]
If you set the `ENH_doStop` attribute on a playable unit and run the mission in multiplayer, all players except the host that select such a unit will be spawned as seagulls for the first time and have to re-select the unit from the lobby to play properly. This can also cause the mission to fail if no respawn is configured.

I've found one example of other players having potentially the same issue [here](https://github.com/kellerkompanie/kellerkompanie-mods/blob/master/addons/common/Cfg3DEN.hpp).

**Comment by R3voA3** [comment]
Thanks for letting me know. I am gonna disable this attribute for multiplayer missions.

Great so see that other folks just delete stuff from the config instead of reporting the issue.

**Comment by R3voA3** [comment]
Fixed
