### ISSUE TITLE
setPos can freeze your game

### ISSUE THREAD

**Issue by felixlinker** [R3voA3/3den-Enhanced#90]
If you change the position of AI that is enclosed in some area it cannot get out of, the game freezes. Was able to reproduce this only with your mod and CBA loaded.

Find an example mission reproducing this behavior attached (it's .txt because github doesn't allow otherwise).

[mission.txt](https://github.com/R3voA3/3den-Enhanced/files/4535336/mission.txt)

**Comment by R3voA3** [comment]
Can you provide repro mission?

**Comment by felixlinker** [comment]
Was able to reproduce *without* CBA and I'm running the stable version, i.e. 1.98.

**Comment by R3voA3** [comment]
Can you send me a complete repro mission?

**Comment by felixlinker** [comment]
There is a repro mission in the first post already. Simply load it and execute the action menu entry.

**Comment by felixlinker** [comment]
Just my two cents (but this is blind guessing): I think it has something to do with path-finding. Did you tweak anything in that direction? It only crashes the game if you start in an area there is no way out of.

**Comment by R3voA3** [comment]
Cannot reproduce the issue. Works as it's supposed to.

**Comment by felixlinker** [comment]
Hm. Taking the latest version from the release seems to fix it. Must be an issue on our side then. Sorry for the fuzz, I will contact our server admin.

And thanks for your time!
