### ISSUE TITLE
Feature Request: Copy Classname to Clipboard Keybind

### ISSUE THREAD

**Issue by G3rrus** [R3voA3/3den-Enhanced#91]
If you're like me and you generally tend to work a lot with classnames of objects it's quite annoying how in the editor you have to right-click the object and then > log > copy classnames to clipboard.

Having a key-bind to fasten things up would be a tremendous addition for an editor enhancing addon.

**Comment by R3voA3** [comment]
What keybind do you have in mind?

**Comment by G3rrus** [comment]
Not sure if a combination with C would work which would obviously be ideal. Something like CTRL + ALT + C.

However CTRL + B should be not assigned to anything and is pretty close to the C button which still makes it fairly ergonomic.

**Comment by R3voA3** [comment]
It seems like shortcuts don't work for custom context menu entries. I have to find a workaround first.
