### ISSUE TITLE
Add better Inventory editor

### ISSUE THREAD

**Issue by klausman** [R3voA3/3den-Enhanced#94]
I used to use this:

https://steamcommunity.com/sharedfiles/filedetails/?id=1124993203

which, while not perfect, was *way* better than tha vanilla inventory editor (in the object's attributes). Unfortunately, it recently broke and I haven't been able to fix it so far. Since that mod is basically abandoned (last release in 2018), it would be great if 3dE would have the same (or better!) functionality.

The main aspects the other mod adds over the basic functionality:

- Search function
- Ability to add and remove bigger amounts (10 at a time)
- Ability to clear one item entirely without clearing the whole container
- Copying container contents between different objects

I'll try and make the other mod work again. If I manage to do so, I may try and port it into 3dE and make a pull requests, but between my lack of skills and lack of time due to work, it may be months.

**Comment by R3voA3** [comment]
I have started working on this today.

- [ ] Search function

- [ ] Ability to add and remove bigger amounts (10 at a time)

- [ ] Ability to clear one item entirely without clearing the whole container

- [ ] Copying container contents between different objects

- [ ] Saving / loading templates

- [ ] More categories for better overview

**Comment by R3voA3** [comment]
Little update:
![20200530123139_1](https://user-images.githubusercontent.com/17484252/83326111-94d1c100-a271-11ea-87e2-1918da121be7.jpg)

The GUI is still WIP so feel free to send feedback =)

**Comment by klausman** [comment]
That looks fantastic! I like that you're making good use of screen realestate. And the "DLC needed" icons are a great addition over the other mod,

Where are the Templates saved? In the player's profile, like ACE3 Saved loadout?

**Comment by klausman** [comment]
Oh, one thing: a "Cancel" option for when one has messed it all up would be nice.

**Comment by R3voA3** [comment]
Templates will be saved in profileNamespace same as the vanilla Arsenal.

A cancel button is planned.

**Comment by R3voA3** [comment]
![20200531001724_1](https://user-images.githubusercontent.com/17484252/83340063-23772a00-a2d4-11ea-99c8-c62ee3c103b0.jpg)

Alright, that's pretty much the final GUI.

**Comment by klausman** [comment]
Excellent work, looking forward to using it :)

Do you have any future things planned for it that will be in later releases?

**Comment by R3voA3** [comment]
Not yet. Let me know if you have an idea.

**Comment by klausman** [comment]
Alright, awaiting a release with bated breath. I will then play around with it, see if I have any feedback. Or do you prefer me packing HEAD up and do some testing before you release?

**Comment by R3voA3** [comment]
Would be awesome if you could test it beforehand, but it's not yet fully working. I'll post a demo mission for testing here as soon as all features are implemented.

**Comment by R3voA3** [comment]
Current Progress:
https://youtu.be/fNUBXsyaao4

**Comment by klausman** [comment]
I had no idea I *needed* that zoom-the-cion feature! Great work!

**Comment by R3voA3** [comment]
@klausman Here's the first test mission. All features are now implemented.
There are still a few bugs, but nothing too serious.

[ENH_InventoryManager_TestMission.vr.zip](https://github.com/R3voA3/3den-Enhanced/files/4736927/ENH_InventoryManager_TestMission.vr.zip)

How to use:
1. Select a vehicle or ammobox
2. Open the debug console
3. In the debug console execute:
```
call compile preprocessFileLineNumbers "t.sqf"; 
call ENH_fnc_IM_onLoad;
```

**Comment by R3voA3** [comment]
#98 Full Code

**Comment by klausman** [comment]
This is great! I tried the test mission and it works like a charm!

**Comment by R3voA3** [comment]
To-Do:

- [ ] Add tooltips

- [ ] Add localisation

- [ ] Check functions for improvements

**Comment by R3voA3** [comment]
Has been implemented.

**Comment by klausman** [comment]
Thanks a bunch! If you're ever in Zurich, Switzerland, I owe you a beer! (or other beverage of choice)
