### ISSUE TITLE
Optional Userconfig PBO

### ISSUE THREAD

**Issue by Freddo3000** [R3voA3/3den-Enhanced#97]
This mod includes *a lot* of stuff, to the point where it starts to feel bloated. Feature creep and all that.

---

As controls and UI elements can't be disabled once in game, I'd suggest adding an optional userconfig .pbo file.

The way I'd imagine it working is as follows
```hpp
class CfgPatches {
	class 3denEnhanced_userconfig
	{
		requiredAddons[] = {"3denEnhanced"};
	};
};

#include "\userconfig\3denEnhanced.hpp"

class Cfg3DEN
{
	class Group
	{
		class AttributeCategories
		{
			#ifdef DISABLE_ATTRIBUTE_GROUPMARKER
			delete ENH_GroupMarker;
			#endif
		};
	};
	class Object
	{
		class AttributeCategories
		{
			class StateSpecial
			{
				class Attributes
				{
					#ifdef
					delete ENH_enableHeadlights;
					#endif
				};
			};
		};
	};
};
```

`\userconfig\3denEnhanced.hpp` looking something like

```hpp
// Uncomment to disable element

//#define DISABLE_GROUP_ATTRIBUTE_GROUPMARKER
//#define DISABLE_OBJECT_ATTRIBUTE_ENABLEHEADLIGHTS
//#define DISABLE_SOMETHING_ATTRIBUTE_XYZ
```

Alternatively, one can do the opposite with userconfig *enabling* features, however that would mean additional setup for the user.

**Comment by R3voA3** [comment]
Interesting idea. I'll have a look at it.

**Comment by R3voA3** [comment]
Problem is, in both cases the user needs to put the userconfig\3denEnhanced.hpp into the root folder, otherwise the game won't start. Which leads to an additional step which needs to be taken.

**Comment by R3voA3** [comment]
Problem is, in both cases the user needs to put the userconfig\3denEnhanced.hpp into the root folder, otherwise the game won't start. Which leads to an additional step which needs to be taken.

**Comment by Freddo3000** [comment]
Yeah, that's why I'm suggesting leaving it as an optional PBO either in a optional folder, or as a separate workshop upload, so that it is not loaded by default.

**Comment by SzwedzikPL** [comment]
There's also an option to use CBA Settings. In next frame after preInit, existance of CBA Settings framework can be checked (this way require of cba_settings won't be necessary), if present we can add options to disable some attributes (this will work only for attributes). Then in `attributeLoad` function setting for attribute can be check, if attribute is disabled we can set attribute control group dimensions to 0, like `_this ctrlSetPosition [0,0,0,0];_this ctrlCommit 0;`. I've done something similar not long ago and worked fine. Downside of this is like i said, this will work only for attributes + settings will be available only if you're using CBA. Just an idea :)

**Comment by R3voA3** [comment]
Well, if that works I don't even need CBA. I could just add some Setting to Eden Editor.

**Comment by R3voA3** [comment]
Sorry, no clue why it was closed.

**Comment by R3voA3** [comment]
`class Cfg3DEN
{
 	class Mission
	{
	/* 	class Preferences
		{
			class AttributeCategories
			{
				class Misc
				{
					class Attributes
					{
					};
				};
			};
		}; */
		class Intel
		{
			class AttributeCategories
			{
				#ifdef HIDE_ENH_VISUALSETTINGS
					delete ENH_VisualSettings;
				#endif
				class Date
				{
					class Attributes
					{
						#ifdef HIDE_ENH_TIMEMULTIPLIER
							delete ENH_TimeMultiplier;
						#endif
					};
				};
			};
		};
		class Scenario
		{
			class AttributeCategories
			{
				#ifdef HIDE_ENH_AIRDROP
					delete ENH_Airdrop;
				#endif
				#ifdef HIDE_ENH_AMBIENTFLYBY
					delete ENH_AmbientFlyby;
				#endif
				#ifdef HIDE_ENH_ESTABLISHINGSHOT
					delete ENH_EstablishingShot;
				#endif
				#ifdef HIDE_ENH_INTROTEXT
					delete ENH_IntroText_Category;//rename later
				#endif
				#ifdef HIDE_ENH_MAPINDICATORS
					delete ENH_MapIndicators;
				#endif
				#ifdef HIDE_ENH_MISSIONENDING
					delete ENH_MissionEnding;
				#endif
				#ifdef HIDE_ENH_SPR
					delete ENH_SPR;
				#endif
				#ifdef HIDE_ENH_VOLUME
					delete ENH_Volume;
				#endif
				class Misc
				{
					class Attributes
					{
					};
				};
			};
		};
		class Multiplayer
		{
			class AttributeCategories
			{
				#ifdef HIDE_ENH_DYNAMICSKILL
					delete ENH_DynamicSkill;
				#endif
				#ifdef HIDE_ENH_DYNAMICGROUPS
					delete ENH_DynamicGroups;
				#endif
				class Respawn
				{
					class Attributes
					{
						#ifdef HIDE_ENH_TICKETSBLUFOR//Doesn't work yet
							delete ENH_TicketsBLUFOR;
						#endif
						#ifdef HIDE_ENH_TICKETSOPFOR
							delete ENH_TicketsOPFOR;
						#endif
						#ifdef HIDE_ENH_TICKETSINDFOR
							delete ENH_TicketsINDFOR;
						#endif
						#ifdef HIDE_ENH_TICKETSCIVFOR
							delete ENH_TicketsCIVFOR;
						#endif
						#ifdef HIDE_ENH_SAVELOADOUT
							delete ENH_SaveLoadout;
						#endif
					};
				};
			};
		};
	};
	class Group
	{
		class AttributeCategories
		{
			class State
			{
				class Attributes
				{
				};
			};
		};
	};
	class Object
	{
		class AttributeCategories
		{
			class StateSpecial
			{
				class Attributes
				{
				};
			};
			class Inventory
			{
				class Attributes
				{
				};
			};
			class State
			{
				class Attributes
				{
				};
			};
		};
	};
};`

`//Environment Attributes
#define HIDE_ENH_VISUALSETTINGS
#define HIDE_ENH_TIMEMULTIPLIER

//General Attributes
#define HIDE_ENH_AIRDROP
#define HIDE_ENH_AMBIENTFLYBY
#define HIDE_ENH_ESTABLISHINGSHOT
#define HIDE_ENH_INTROTEXT
#define HIDE_ENH_MAPINDICATORS
#define HIDE_ENH_MISSIONENDING
#define HIDE_ENH_SPR
#define HIDE_ENH_VOLUME

//Multiplayer Attributes
#define HIDE_ENH_DYNAMICSKILL
#define HIDE_ENH_TICKETSBLUFOR
#define HIDE_ENH_TICKETSOPFOR
#define HIDE_ENH_TICKETSINDFOR
#define HIDE_ENH_TICKETSCIVFOR
#define HIDE_ENH_SAVELOADOUT
#define HIDE_ENH_DYNAMICGROUPS`

I have started working on this now. Two things I am not yet sure about:

- [ ] How can I delete entries from the menus trip and context menu. Simply deleting them will leave an empty button area and I don't know if I can delete entries from the `items[]={};` array.

- [ ] Wether or not to deliver it as standalone modification or as an optional folder inside 3den Enhanced.

@Freddo3000 What do you think?

**Comment by Freddo3000** [comment]
It would possibly be a bit convoluted, but you could do a bunch of sub-configs editing the items[] array with ifdef statements.

```
#ifndef disable_something
items[] += {"something"};
#endif
```

https://community.bistudio.com/wiki/CfgPatches#Sub-folders  
https://community.bistudio.com/wiki/Config.cpp/bin_File_Format#Many_configs.2C_same_pbo

On the second question, I'd suggest keeping it as a separate workshop entry so that Steam doesn't overwrite it whenever you update the mod.

@R3voA3

**Comment by R3voA3** [comment]
I might have found a better solution for the menu strip.

https://community.bistudio.com/wiki/menuDelete

Need to check if there are similar commands for the context menu.

**Comment by R3voA3** [comment]
Has been implemented. Unfortunately context menu entries cannot be hidden easily.

**Comment by R3voA3** [comment]
I am reopening this issue because there might be a better way to do this in the future.

There might be a way in the future to make userconfigs optional. See
![image](https://user-images.githubusercontent.com/17484252/102695109-9b338480-4225-11eb-98e2-837b3701f0d9.png)

This could replace ENHO mod.

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/102915769-9f101280-4482-11eb-88aa-5aebe1027266.png)

**Comment by Freddo3000** [comment]
Would probably be neater with `#if __has_include`

**Comment by Freddo3000** [comment]
Related ticket: https://feedback.bistudio.com/T153547

**Comment by R3voA3** [comment]
So fileExists only works for userconfig files when -filePatching is enabled.

**Comment by R3voA3** [comment]
Seems like my initial idea doesn't work

`#if __has_include("\userconfig\ENH_Config.hpp")
  #include "\userconfig\ENH_Config.hpp"
#endif`

@Freddo3000 Any suggetions for a better approach?

Also I saw you note on https://community.bistudio.com/wiki/High_Command
I started working on an Arma 3 version https://community.bistudio.com/wiki/User_talk:R3vo

Feel free to add suggestions ;)

**Comment by Freddo3000** [comment]
> 
> 
> Seems like my initial idea doesn't work
> 
> `#if __has_include("\userconfig\ENH_Config.hpp")`
> `#include "\userconfig\ENH_Config.hpp"`
> `#endif`
> 

On dev branch or? You might need to leave it unbinarized.

> Also I saw your note on [community.bistudio.com/wiki/High_Command](https://community.bistudio.com/wiki/High_Command)
> I started working on an Arma 3 version [community.bistudio.com/wiki/User_talk:R3vo](https://community.bistudio.com/wiki/User_talk:R3vo)
> 
> Feel free to add suggestions ;)

Maybe add a note regarding the chain-of-command functionality, even though it is admittedly pretty bad.

**Comment by R3voA3** [comment]
> On dev branch or? You might need to leave it unbinarized.
It is, and yes on dev branch. It seems to be that #include can not be inside a #if block =/

> Maybe add a note regarding the chain-of-command functionality, even though it is admittedly pretty bad.
I have no clue how it works. Seems like there are no functions attached to the module which I could use to look it up.

**Comment by Freddo3000** [comment]
> 
> 
> > On dev branch or? You might need to leave it unbinarized.
> 
> It is, and yes on dev branch. It seems to be that #include can not be inside a #if block =/

@dedmen ?


> > Maybe add a note regarding the chain-of-command functionality, even though it is admittedly pretty bad.
> 
> I have no clue how it works. Seems like there are no functions attached to the module which I could use to look it up.

It works by chaining up high command modules, like you have another commander under your command. So `unitA > Leader > Subordinate > unitB > Leader > Subordinate > unitC...`

**Comment by R3voA3** [comment]
I did some more testing and this is what I get.

`#if __has_include("\userconfig\ENH_Config.hpp")`
`  #include "\userconfig\ENH_Config.hpp"`
`#endif`

1. If file is present, the following error message is shown (filePatching enabled and disabled)
![image](https://user-images.githubusercontent.com/17484252/106887138-06a5b880-66e5-11eb-8889-37ecc59ad1f4.png)

2. If file is *not* present, the game starts normally (filePatching enabled and disabled)

**Comment by Freddo3000** [comment]
Well that is certainly an interesting interaction. You should probably post it to https://feedback.bistudio.com/T153547

**Comment by R3voA3** [comment]
> Well that is certainly an interesting interaction. You should probably post it to https://feedback.bistudio.com/T153547, as it sounds like a bug.

I wrote dedmen already.

**Comment by R3voA3** [comment]
![image](https://user-images.githubusercontent.com/17484252/107013313-7a55cd00-679a-11eb-87fa-29420c08edfc.png)
Needs testing when it's available.

**Comment by R3voA3** [comment]
Done
