### ISSUE TITLE
Texturefinder double textureentries 

### ISSUE THREAD

**Issue by shukari** [R3voA3/3den-Enhanced#99]
needs to be not case-insensitive
https://github.com/R3voA3/3den-Enhanced/blob/4935419b4f20054ff4325f64db143b32606ecd7f/3denEnhanced/functions/GUI/textureFinder/fn_textureFinder_findTextures.sqf#L64

![20200626130131_1](https://user-images.githubusercontent.com/7529291/85850742-aee9bb00-b7ad-11ea-85bd-3946b0268f3c.jpg)

**Comment by R3voA3** [comment]
Thanks for the report.

**Comment by R3voA3** [comment]
Solved (4b2751c56d022bb16537ad28a78ee756447bc3f6)
